### PR TITLE
Make winfs-injector backwards compatible

### PR DESCRIPTION
**Pull request by chendrix**
This is the PR meant to fix [#159676912](https://www.pivotaltracker.com/n/projects/2145041/stories/159676912)

In short, because of the various ways we've embedded the fs-release, and the various ways that the IMAGE_TAG can be present inside of that embedded release, our most recent builds of winfs-injector were only valid for very specific versions of tiles.

This is a poor operator experience, and even though it's hairy, we can use heuristics to:
- grab the appropriate embedded fs-release (whatever folder exists inside of `/embed/`)
- parse the name of the release (`/config/final.yml`)
- parse the version of the release (`/VERSION`)
- parse the stemcell line from the release name
  - `windows2016fs` => `1709`
  - `windows1803fs` => `1803`
  - any other `windows(\d{4})fs` => `$1`

### CODE REVIEW

**Comment by ljfranklin** [comment]
@chendrix going forward will the IMAGE_TAG location be `windowsfs/IMAGE_TAG` or is `windowsfs/$STEMCELL_VERSION/IMAGE_TAG` the new location?

**Comment by chendrix** [comment]
@ljfranklin my understanding is the latter.

**Comment by ljfranklin** [comment]
@chendrix LGTM 👍 I'll leave it to you to merge, not sure if you wanted to do any manual acceptance before merging into master.

**Comment by chendrix** [comment]
Alright I did some manual smoke testing and found an issue that was fixed. Now I'm going to merge and let @mcwumbly do acceptance

**Pull request merged**
